# configs/swinunetr_combined.yaml

project_name: "Stroke-Segmentation"
model_info:
  name: "swinunetr"          # choices: [unet, unetpp, mobilevit, swinunetr]
  input_type: "combined"     # choices: [single, combined]
  in_channels: 2             # If DWI and ADC are used together, input channels should be 2.
  out_channels: 1            # A single channel binary mask

training:
  epochs: 100
  batch_size: 2
  learning_rate: 0.001
  optimizer: "Adam"
  loss_function: "BCEDice"

data:
  image_size: [32, 256, 256] # Image size after interpolation
  data_path: "./dataset/stroke_data"
  checkpoint_dir: "./weights/swinunetr_best.pth"
